### ISSUE TITLE
Only works with YAML files

### ISSUE THREAD

**Issue by robinbowes** [stefanandres/hiera_dump#1]
Nice idea, but at first glance it seems to load the YAML directly so it will only work with plain YAML files, and not encrypted YAML, or any other valid hiera backend?

**Comment by stefanandres** [comment]
Yeah, it only works for the yaml backend. Other backends would need explicit code.
hiera-eyaml should work for encrypted files, since it's only encrypting the values though. hiera-gpg will probably not work, because it cannot read the key value pairs from the file. One could probably put some effort for that though if needed.
